### PR TITLE
Discover battery path, so the battery graph works on the tablet. 

### LINKED ISSUE #11: Make it work on Tablet
Utilize ```/sys/class/power_supply/dollar_cove_battery```

### PR DESCRIPTION
**Pull request by abranson**
Fixes #11

### CODE REVIEW

**Comment by custodian** [comment]
Seems legit, merged.

**Comment by abranson** [comment]
Great! I'd pushed a x86 build to openrepos, but will remove it if you want to do so instead.

**Comment by custodian** [comment]
I doubt I will ever get Jolla tablet shipped to me, so feel free to push x86 version.

**Comment by abranson** [comment]
Ok, hope you get one. Would you be ok if I pushed x86 Warehouse too? That works quite well - there's no filtering on architecture on the server side but that's not a huge problem.

**Comment by custodian** [comment]
Be my guest.

**Pull request merged**
